services:
  lambda-scrape:
    image: lambda-scrape:local
    env_file:
      - .env
    build:
      context: .
      dockerfile: functions/scrape/Dockerfile
      target: lambda
    volumes:
      - ./functions/scrape/src:/var/task
      - ./shared:/var/task/shared
    ports:
      - "9010:8080"
    
  lambda-standardize-html:
    image: lambda-standardize-html:local
    env_file:
    - .env
    build:
      context: .
      dockerfile: functions/standardize-html/Dockerfile
      target: lambda
    volumes:
      - ./functions/standardize-html/src:/var/task
      - ./shared:/var/task/shared
    ports:
      - "9030:8080"

  lambda-tokenize:
    image: lambda-tokenize:local
    env_file:
    - .env
    build:
      context: .
      dockerfile: functions/tokenize/Dockerfile
      target: local
    volumes:
      - ./functions/tokenize/src/app.py:/var/task/app.py
      - ./functions/tokenize/src/main.py:/var/task/main.py
      - ./functions/tokenize/src/data/ignored_nouns.txt:/var/task/data/ignored_nouns.txt
      - ./shared:/var/task/shared

  lambda-create-embeddings:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_ECR_REPO}/lambda-create-embeddings:0.1
    env_file:
    - .env
    build:
      context: .
      target: local
      dockerfile: functions/create-embeddings/Dockerfile
    volumes:
      - ./functions/create-embeddings/src/app.py:/var/task/app.py
      - ./functions/create-embeddings/src/create_embeddings.py:/var/task/create_embeddings.py
      - ./functions/create-embeddings/src/constants.py:/var/task/constants.py
      - ./functions/create-embeddings/src/ppmi_svd.py:/var/task/ppmi_svd.py
      - ./shared:/var/task/shared

  lambda-publish:
    image: lambda-publish:local
    env_file:
    - .env
    build:
      context: .
      target: local
      dockerfile: functions/publish/Dockerfile
    volumes:
      - ./functions/publish/src/app.py:/var/task/app.py
      - ./functions/publish/src/publish.py:/var/task/publish.py
      - ./shared:/var/task/shared

  lambda-api:
    image: lambda-api:local
    env_file:
    - .env
    build:
      context: .
      dockerfile: functions/api/Dockerfile
      target: local
    volumes:
      - ./functions/api/src:/var/task
      - ./shared:/var/task/shared
    ports:
      - "8000:8000"
