services:
  lambda-scrape:
    image: lambda-scrape:local
    env_file:
      - .env
    build:
      context: .
      dockerfile: functions/scrape/Dockerfile
      target: lambda
    volumes:
      - ./functions/scrape/src:/var/task
      - ./shared:/var/task/shared
    ports:
      - "9010:8080"
    
  lambda-standardize-html:
    image: lambda-standardize-html:local
    env_file:
    - .env
    build:
      context: .
      dockerfile: functions/standardize-html/Dockerfile
      target: lambda
    volumes:
      - ./functions/standardize-html/src:/var/task
      - ./shared:/var/task/shared
    ports:
      - "9030:8080"

  lambda-tokenize:
    image: lambda-tokenize:local
    env_file:
    - .env
    build:
      context: .
      dockerfile: functions/tokenize/Dockerfile
      target: local
    volumes:
      - ./functions/tokenize/src/app.py:/var/task/app.py
      - ./functions/tokenize/src/main.py:/var/task/main.py
      - ./functions/tokenize/src/ignored_nouns.txt:/var/task/ignored_nouns.txt

  lambda-train-kvector:
    image: lambda-train-kvector:local
    env_file:
    - .env
    build:
      context: .
      target: local
      dockerfile: functions/train-kvector/Dockerfile
    volumes:
      - ./functions/train-kvector/src/app.py:/var/task/app.py
      - ./functions/train-kvector/src/main.py:/var/task/main.py

  lambda-align-kvectors:
    image: lambda-align-kvectors:local
    env_file:
    - .env
    build:
      context: .
      dockerfile: functions/align-kvectors/Dockerfile
    volumes:
      - ./functions/align-kvectors/src/app.py:/var/task/app.py
      - ./functions/align-kvectors/src/create_book_centroid.py:/var/task/create_book_centroid.py
      - ./functions/align-kvectors/src/procrustes_utils.py:/var/task/procrustes_utils.py

  lambda-publish:
    image: lambda-publish:local
    env_file:
    - .env
    build:
      context: .
      target: local
      dockerfile: functions/publish/Dockerfile
    volumes:
      - ./functions/publish/src/app.py:/var/task/app.py
      - ./functions/publish/src/publish_to_api.py:/var/task/publish_to_api.py
      - ./functions/publish/src/publish_utils.py:/var/task/publish_utils.py

  lambda-api:
    image: lambda-api:local
    env_file:
    - .env
    build:
      context: .
      dockerfile: functions/api/Dockerfile
      target: local
    volumes:
      - ./functions/api/src:/var/task
      - ./shared:/var/task/shared
    ports:
      - "8000:8000"
