[pytest]
testpaths = tests
pythonpath = src . ../../
addopts =
    --cov=app
    --cov=main
    --cov-report=term-missing
    --cov-fail-under=85
filterwarnings =
    ignore::DeprecationWarning:pydantic.*
    ignore::DeprecationWarning:fastapi_cache.*
    ignore::DeprecationWarning:mangum.*